# Generated by Django 3.2.4 on 2021-07-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=70)),
                ('texto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muevelasnalgas.deporte')),
                ('favoritos', models.ManyToManyField(blank=True, related_name='_muevelasnalgas_comunidad_favoritos_+', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='_muevelasnalgas_comunidad_miembros_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('descripcion', models.CharField(max_length=150)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muevelasnalgas.tipozona')),
            ],
            options={
                'unique_together': {('lat', 'lng')},
            },
        ),
    ]
