# Generated by Django 3.2.4 on 2021-07-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muevelasnalgas', '0003_zona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipozona',
            name='variable',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipozona',
            name='icono',
            field=models.CharField(max_length=50),
        ),
    ]
